// src/renderer/view/components/base/VDialogBase.tsx
import * as vca from "vue-tsx-support/lib/vca";
import p from "vue-strict-prop";
import { DialogState } from "view/store/dialogModule";
import VButton from "./VButton";
import VModal, { ModalContainerClass } from "./VModal";
import * as emotion from "emotion";
import { createElement } from "@vue/composition-api";
const css = emotion.css;

export default vca.component({
  name: "VDialogBase",
  props: {
    state: p.ofObject<DialogState>().required,
    accept: p.ofFunction<{ buttonId: string }, void>().required,
    cancel: p.ofFunction<() => void>().required
  },
  setup(p) {
    return () => {
      const opt = p.state.options;
      if (!opt) {
        return <div />;
      }
      const { accept, cancel } = p;
      const buttons = opt.buttons.map(b => (
        <VButton
          key={b.name}
          mini
          primary={b.primary}
          accent={b.accent}
          action={() => accept({ buttonId: b.name })}
        >
          <span staticClass="md-title">{b.text}</span>
        </VButton>
      ));
      return (
        <VModal staticClass={style.dialogBase} title={opt.title} close={cancel}>
          {opt.renderContent(createElement)}
          <template slot="footer-buttons">
            {buttons}
            <VButton key="__CANCEL__" mini action={cancel}>
              <span staticClass="md-title">CANCEL</span>
            </VButton>
          </template>
        </VModal>
      );
    };
  }
});

const style = {
  dialogBase: css`
    .${ModalContainerClass} {
      margin: auto;
      min-width: 400px;
      box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.4);
      transition: all 0.2s ease;
    }

    &.modal-enter,
    &.modal-leave-to {
      .${ModalContainerClass} {
        transform: scale(1.05);
        opacity: 0;
      }
    }
  `
};

// src/renderer/view/common/components/VDialogBase.vue
<script lang="tsx">
import { VNode } from "vue";
import * as tsx from "vue-tsx-support";
import p from "vue-strict-prop";
import { DialogState, DialogActions } from "../storeModules/dialog";
import VButton from "./VButton.vue";
import VModal from "./VModal.vue";

export default tsx.component(
  // @vue/component
  {
    name: "VDialogBase",
    props: {
      state: p.ofObject<DialogState>().required,
      actions: p.ofObject<DialogActions>().required
    },
    render(): VNode {
      const opt = this.state.options;
      if (!opt) {
        return <div />;
      }
      const { accept, cancel } = this.actions;
      const buttons = opt.buttons.map(b => (
        <VButton
          key={b.name}
          mini
          primary={b.primary}
          accent={b.accent}
          onClick={() => accept(b.name)}
        >
          <span staticClass="md-title">{b.text}</span>
        </VButton>
      ));
      const s = this.$style;
      return (
        <VModal
          staticClass={s.dialogBase}
          title={opt.title}
          containerClass={s.container}
          onClose={cancel}
        >
          {opt.renderContent(this.$createElement)}
          <template slot="footer-buttons">
            {buttons}
            <VButton key="__CANCEL__" mini onClick={cancel}>
              <span staticClass="md-title">CANCEL</span>
            </VButton>
          </template>
        </VModal>
      );
    }
  },
  ["state", "actions"]
);
</script>

<style lang="scss" module>
.container {
  margin: auto;
  min-width: 400px;
  box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.4);
  transition: all 0.2s ease;
}

.dialogBase:global(.modal-enter),
.dialogBase:global(.modal-leave-to) {
  .container {
    transform: scale(1.05);
    opacity: 0;
  }
}
</style>
