// src/renderer/view/components/LogTable.tsx
import * as vca from "vue-tsx-support/lib/vca";
import {
  vtableOf,
  VtableColumn,
  Vtable,
  VtableEventsOn,
  VtableSlotCellProps
} from "vue-vtable";
import LogTableCellGraph from "./LogTableCellGraph";
import LogTableCellSummary from "./LogTableCellSummary";
import { LogItem } from "../mainTypes";
import { css } from "@emotion/css";
import { GitHash } from "./GitHash";
import { MonoSpan } from "./base/mono";
import { formatDateL } from "core/date";
import { required } from "./base/prop";
import { watch, ref } from "@vue/composition-api";

const VtableT = vtableOf<LogItem>();

const columns: readonly VtableColumn[] = Object.freeze([
  {
    id: "graph",
    defaultWidth: 120,
    minWidth: 40
  },
  {
    id: "id",
    defaultWidth: 80,
    minWidth: 40
  },
  {
    id: "author",
    defaultWidth: 120,
    minWidth: 40
  },
  {
    id: "date",
    defaultWidth: 100,
    minWidth: 40
  },
  {
    id: "comment",
    defaultWidth: 600,
    className: "flex--expand",
    minWidth: 200
  }
]);

export default vca.component({
  name: "LogTable",
  props: {
    items: required<readonly LogItem[]>(Array),
    rowHeight: required(Number),
    selectedIndex: required(Number),
    widths: required<Record<string, number>>(Object)
  },
  setup(p, ctx: vca.SetupContext<VtableEventsOn<LogItem>>) {
    const vtableRef = ref<Vtable<LogItem> | null>(null);
    watch(
      () => p.selectedIndex,
      newValue => {
        if (vtableRef.value) {
          vtableRef.value.ensureVisible(newValue);
        }
      }
    );

    const renderCell = (payload: VtableSlotCellProps<LogItem>) => {
      const { columnId, item } = payload;
      switch (columnId) {
        case "graph":
          return (
            <LogTableCellGraph graph={item.graph} gridWidth={12} height={24} />
          );
        case "id":
          return <GitHash hash={item.commit.id} />;
        case "author":
          return item.commit.author;
        case "date":
          return <MonoSpan>{formatDateL(item.commit.date)}</MonoSpan>;
        case "comment":
          return <LogTableCellSummary commit={item.commit} refs={item.refs} />;
        default:
          return undefined;
      }
    };
    const getItemKey = (item: LogItem) => item.commit.id;
    const getRowClass = (_item: LogItem, index: number) =>
      index === p.selectedIndex ? style.selectedRow : "";

    return () => (
      <VtableT
        ref={vtableRef}
        staticClass={style.container}
        items={p.items}
        columns={columns}
        widths={p.widths}
        rowHeight={p.rowHeight}
        rowStyleCycle={2}
        getItemKey={getItemKey}
        getRowClass={getRowClass}
        {...{ on: ctx.listeners }}
        scopedSlots={{ cell: renderCell }}
      />
    );
  }
});

const style = {
  container: css`
    .vlist-row {
      user-select: none;
      cursor: default;
      &:nth-child(2n) {
        background-color: #282828;
      }
      &:hover {
        background-color: #383838;
      }
    }

    .vlist-header-row {
      border-bottom: solid 1px #aaa;
      user-select: none;
      cursor: default;
    }

    .vtable-splitter {
      border-right: solid 1px #555;
    }

    .vtable-dragging-splitter {
      background-color: #888;
    }
  `,
  selectedRow: css`
    background-color: #484848;
  `
};

export { style };

// src/renderer/view/main/components/LogTable.vue
<script lang="tsx">
import { VNode } from "vue";
import * as moment from "moment";
import * as tsx from "vue-tsx-support";
import { vtableOf, VtableColumn, Vtable, VtableEventsOn } from "vue-vtable";
import p from "vue-strict-prop";
import LogTableCellGraph from "./LogTableCellGraph.vue";
import LogTableCellSummary from "./LogTableCellSummary.vue";
import { LogItem } from "../mainTypes";

const VtableT = vtableOf<LogItem>();

export default tsx.componentFactoryOf<VtableEventsOn<LogItem>>().create(
  // @vue/component
  {
    name: "LogTable",
    props: {
      items: p.ofRoArray<LogItem>().required,
      rowHeight: p(Number).required,
      selectedIndex: p(Number).required,
      widths: p.ofRoArray<number>().optional
    },
    computed: {
      columns(): VtableColumn[] {
        return [
          {
            title: "graph",
            defaultWidth: 120,
            minWidth: 40
          },
          {
            title: "id",
            defaultWidth: 80,
            minWidth: 40
          },
          {
            title: "author",
            defaultWidth: 120,
            minWidth: 40
          },
          {
            title: "date",
            defaultWidth: 100,
            minWidth: 40
          },
          {
            title: "comment",
            defaultWidth: 600,
            className: "flex--expand",
            minWidth: 200
          }
        ];
      }
    },
    watch: {
      selectedIndex(newValue: number) {
        (this.$refs["vtable"] as Vtable<LogItem>).ensureVisible(newValue);
      }
    },
    methods: {
      renderCell(columnId: string, item: LogItem): VNode | string {
        switch (columnId) {
          case "graph":
            return (
              <LogTableCellGraph
                graph={item.graph}
                gridWidth={12}
                height={24}
              />
            );
          case "id":
            return (
              <span class="fontfamily--monospace" title={item.commit.id}>
                {item.commit.id.substring(0, 8)}
              </span>
            );
          case "author":
            return item.commit.author;
          case "date":
            return (
              <span class="fontfamily--monospace">
                {moment(item.commit.date)
                  .local()
                  .format("L")}
              </span>
            );
          case "comment":
            return (
              <LogTableCellSummary commit={item.commit} refs={item.refs} />
            );
          default:
            return "";
        }
      }
    },
    render(): VNode {
      const { rowHeight, selectedIndex } = this;
      const s = this.$style;
      return (
        <VtableT
          ref="vtable"
          staticClass={s.container}
          items={this.items}
          columns={this.columns}
          initialWidths={this.widths}
          rowHeight={rowHeight}
          rowStyleCycle={2}
          getItemKey={item => item.commit.id}
          getRowClass={(_item, index) =>
            index === selectedIndex ? s.selectedRow : ""
          }
          {...{ on: this.$listeners }}
          onColumnresize={arg => this.$emit("update:widths", arg.widths)}
          scopedSlots={{
            cell: p => [this.renderCell(p.columnId, p.item)]
          }}
        />
      );
    }
  },
  ["items", "rowHeight", "selectedIndex"]
);
</script>

<style lang="scss" module>
.container {
  :global {
    .vlist-row:nth-child(2n) {
      background-color: #282828;
    }

    .vlist-row:hover {
      background-color: #383838;
    }

    .vlist-header-row {
      border-bottom: solid 1px #aaa;
    }

    .vtable-splitter {
      border-left: solid 1px #555;
    }

    .vtable-dragging-splitter {
      background-color: #888;
    }
  }

  .selectedRow {
    background-color: #484848;
  }
}
</style>
