// src/renderer/view/main/components/BaseLayout.vue
<script lang="tsx">
import Vue, { VNode } from "vue";
import * as tsx from "vue-tsx-support";
import { componentWithStore } from "../store";
import p from "vue-strict-prop";
import VDialogBase from "view/common/components/VDialogBase.vue";
import VIconButton from "view/common/components/VIconButton.vue";

interface MainLayoutProps {
    title: string;
}

export default componentWithStore({
    name: "BaseLayout",
    props: {
        title: p(String).required
    },
    data() {
        return { menuVisible: false };
    },
    methods: {
        toggleMenu(): void {
            this.menuVisible = !this.menuVisible;
        }
    },
    render(): VNode {
        return (
            <div staticClass="main-container">
                <md-app md-mode="fixed">
                    <md-app-toolbar staticClass="md-primary" md-dense>
                        <VIconButton mini onClick={this.toggleMenu}>
                            menu
                        </VIconButton>
                        <span staticClass="main-title md-title" style={{margin: 0, flex: 1}}>
                            {this.title}
                        </span>
                        <div staticClass="md-toolbar-section-end">
                            {this.$slots["titlebar-buttons"]}
                        </div>
                    </md-app-toolbar>

                    <md-app-drawer md-active={this.menuVisible} md-fixed>
                        <md-toolbar staticClass="md-transparent" md-elevation={0}>
                            <div staticClass="md-toolbar-section-end">
                                <VIconButton mini onClick={this.toggleMenu}>
                                    keyboard_arrow_left
                                </VIconButton>
                            </div>
                        </md-toolbar>
                        <md-list {...{ on: { "!click": this.toggleMenu } }}>
                            {this.$slots["drawer-navigations"]}
                        </md-list>
                    </md-app-drawer>

                    <md-app-content style={{position: "relative", padding: "1px"}}>
                        <div staticClass="main-content">
                            {this.$slots["default"]}
                        </div>
                    </md-app-content>
                </md-app>

                <router-view />
                <VDialogBase state={this.$store.state.dialog} actions={this.$store.actions.dialog} />
            </div>
        );
    }
});
</script>

<style>
.md-app {
    flex: 1;
}

.md-app-toolbar {
    padding: 0 4px;
}

.main-container {
    display: flex;
    flex-flow: column nowrap;
    flex: 1;
}

.main-content {
    display: flex;
    flex-direction: row;
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    box-sizing: border-box;
    padding: 4px;
}

.main-title {
    margin: 0;
}
</style>

// src/renderer/view/components/BaseLayout.tsx
import {
  useErrorReporterModule,
  useDialogModule,
  useRootModule
} from "../store";
import * as vca from "vue-tsx-support/lib/vca";
import VDialogBase from "./base/VDialogBase";
import VIconButton from "./base/VIconButton";
import TitleBarButton from "./TitleBarButton";
import VNotification from "./base/VNotification";
import PreferencePanel from "./PreferencePanel";
import { __capture, __sync } from "view/utils/modifiers";
import { MdList } from "./base/md";
import { css } from "@emotion/css";
import { ref, computed } from "@vue/composition-api";
import { evaluateSlot } from "core/utils";
import { required } from "./base/prop";

export default vca.component({
  name: "BaseLayout",
  props: {
    title: required(String)
  },
  setup(p, ctx) {
    const rootModule = useRootModule();
    const errorReporterModule = useErrorReporterModule();
    const dialogModule = useDialogModule();
    const menuVisible = ref(false);
    const dialogState = computed(() => ({ ...dialogModule.state }));
    const toggleMenu = () => {
      menuVisible.value = !menuVisible.value;
    };
    return () => {
      return (
        <div staticClass={style.container}>
          <md-app md-mode="fixed">
            <md-app-drawer md-fixed md-active={__sync(menuVisible.value)}>
              <md-toolbar staticClass="md-transparent" md-elevation={0}>
                <div staticClass="md-toolbar-section-end">
                  <VIconButton mini action={toggleMenu}>
                    keyboard_arrow_left
                  </VIconButton>
                </div>
              </md-toolbar>
              <MdList nativeOn-click={__capture(toggleMenu)}>
                {evaluateSlot(ctx, "drawer-navigations")}
              </MdList>
            </md-app-drawer>

            <md-app-content staticClass={style.contentWrapper}>
              <div staticClass={style.titleBar}>
                <TitleBarButton action={toggleMenu}>menu</TitleBarButton>
                <span style="flex: 1">{p.title}</span>
                {evaluateSlot(ctx, "titlebar-buttons")}
              </div>
              <div staticClass={style.content}>
                {evaluateSlot(ctx, "default")}
              </div>
            </md-app-content>
          </md-app>

          <PreferencePanel
            active={rootModule.state.preferenceShown}
            initialConfig={rootModule.state.config}
            hide={rootModule.actions.hidePreference}
            save={rootModule.actions.resetConfig}
          />
          <VNotification
            icon="info"
            message={rootModule.state.notification}
            color="primary"
            hide={rootModule.actions.hideNotification}
          />
          <VNotification
            icon="warning"
            message={errorReporterModule.getters.message}
            color="accent"
            hide={errorReporterModule.actions.clear}
          />
          <VDialogBase
            state={dialogState.value}
            accept={dialogModule.actions.accept}
            cancel={dialogModule.actions.cancel}
          />
        </div>
      );
    };
  }
});

const style = {
  container: css`
    display: flex;
    flex-flow: column nowrap;
    flex: 1;
    .md-app {
      flex: 1;
    }
    .md-app-toolbar {
      padding: 0 4px;
    }
  `,
  title: css`
    margin: 0 !important;
    flex: 1;
  `,
  contentWrapper: css`
    position: relative;
    padding: 1px;
  `,
  titleBar: css`
    position: absolute;
    display: flex;
    flex-flow: row nowrap;
    left: 0;
    top: 0;
    right: 0;
    height: 28px;
    line-height: 28px;
    background-color: #2a2a2a;
    color: #888;
    font-size: 18px !important;
  `,
  content: css`
    display: flex;
    flex-direction: row;
    position: absolute;
    left: 0;
    right: 0;
    top: 28px;
    bottom: 0;
    box-sizing: border-box;
    padding: 4px;
  `
};
