// src/renderer/view/components/FileTable.vue
<script lang="tsx">
import { VNode } from "vue";
import * as tsx from "vue-tsx-support";
import p from "vue-strict-prop";
import { vtableOf, VtableColumn, VtableEventsOn } from "vue-vtable";
import * as md from "view/utils/md-classes";

const Vtable = vtableOf<FileEntry>();

const fileColumns: VtableColumn[] = [
  {
    title: "",
    className: md.BODY2,
    defaultWidth: 24,
    minWidth: 24
  },
  {
    title: "path",
    className: "flex--expand " + md.BODY2,
    defaultWidth: 200,
    minWidth: 100
  }
];

// @vue/component
export default tsx.componentFactoryOf<VtableEventsOn<FileEntry>>().create({
  name: "FileTable",
  props: {
    files: p.ofRoArray<FileEntry>().required,
    widths: p.ofRoArray<number>().optional
  },
  data() {
    return { selectedFile: "" };
  },
  methods: {
    getFileKey(item: FileEntry): string {
      return item.path;
    },
    renderCell(columnId: string, item: FileEntry) {
      if (columnId === "path") {
        return item.path;
      } else {
        return item.statusCode;
      }
    }
  },
  render(): VNode {
    return (
      <div staticClass={this.$style.container}>
        <Vtable
          items={this.files}
          columns={fileColumns}
          initialWidths={this.widths}
          rowHeight={24}
          getItemKey={this.getFileKey}
          onColumnresize={args => this.$emit("update:widths", args.widths)}
          getRowClass={arg => {
            return arg.path === this.selectedFile
              ? "vtable-row-selected"
              : "vtable-row";
          }}
          onRowclick={arg => {
            this.selectedFile = arg.item.path;
          }}
          scopedSlots={{
            cell: p => this.renderCell(p.columnId, p.item)
          }}
          {...{ on: this.$listeners }}
        />
      </div>
    );
  }
});
</script>

<style lang="scss" module>
.container {
  display: flex;
  flex: 1;

  :global {
    .vlist-container {
      display: flex;
      margin: 4px 2px;
      background-color: #333;
    }

    .vlist-row {
      font-family: var(--monospace-fontfamily);
      &:hover {
        background-color: #4c4c4c;
      }
    }

    .vtable-row-selected {
      background-color: #484848;
    }

    .vtable-splitter {
      border-left: solid 1px #222;
    }

    .vtable-dragging-splitter {
      background-color: #222;
    }

    .vlist-header-row {
      border-bottom: solid 2px #222;
    }
  }
}
</style>

// src/renderer/view/components/FileTable.tsx
import * as vca from "vue-tsx-support/lib/vca";
import {
  vtableOf,
  VtableColumn,
  VtableEventsOn,
  VtableSlotCellProps,
  RowClickEventArgs
} from "vue-vtable";
import * as md from "view/utils/md-classes";
import * as emotion from "emotion";
import { required } from "./base/prop";
import { ref } from "@vue/composition-api";
const css = emotion.css;

const Vtable = vtableOf<FileEntry>();

const fileColumns: readonly VtableColumn[] = Object.freeze([
  {
    id: "status",
    title: "",
    className: md.BODY2,
    defaultWidth: 24,
    minWidth: 24
  },
  {
    id: "path",
    className: "flex--expand " + md.BODY2,
    defaultWidth: 200,
    minWidth: 100
  }
]);

// @vue/component
export default vca.component({
  name: "FileTable",
  props: {
    files: required<readonly FileEntry[]>(),
    widths: required<Record<string, number>>(Object)
  },
  setup(p, ctx: vca.SetupContext<VtableEventsOn<FileEntry>>) {
    const selectedFile = ref("");
    const getFileKey = (item: FileEntry) => item.path;
    const getRowClass = (item: FileEntry) =>
      item.path === selectedFile.value ? "vtable-row-selected" : "vtable-row";
    const getCellValue = (arg: VtableSlotCellProps<FileEntry>) =>
      arg.columnId === "path" ? arg.item.path : arg.item.statusCode;
    const onRowclick = (arg: RowClickEventArgs<FileEntry>) => {
      selectedFile.value = arg.item.path;
    };
    return () => (
      <div staticClass={style.container}>
        <Vtable
          items={p.files}
          columns={fileColumns}
          widths={p.widths}
          rowHeight={24}
          getItemKey={getFileKey}
          getRowClass={getRowClass}
          onRowclick={onRowclick}
          scopedSlots={{
            cell: getCellValue
          }}
          {...{ on: ctx.listeners }}
        />
      </div>
    );
  }
});

const style = {
  container: css`
    display: flex;
    flex: 1;

    .vlist-container {
      display: flex;
      margin: 4px 2px;
      background-color: #333;
    }

    .vlist-row {
      font-family: var(--monospace-fontfamily);
      user-select: none;
      cursor: default;
      &:hover {
        background-color: #4c4c4c;
      }
    }

    .vtable-row-selected {
      background-color: #484848;
    }

    .vtable-splitter {
      border-left: solid 1px #222;
    }

    .vtable-dragging-splitter {
      background-color: #222;
    }

    .vlist-header-row {
      border-bottom: solid 2px #222;
      user-select: none;
      cursor: default;
    }
  `
};
