// src/renderer/view/main/components/SideBarRemotes.vue
<script lang="tsx">
import { VNode } from "vue";
import * as tsx from "vue-tsx-support";
import SideBarBase from "./SideBarBase.vue";

export default tsx.component({
    name: "SideBarRemotes",
    render(): VNode {
        return (
            <SideBarBase title="Remotes">
                Not implemented
            </SideBarBase>
        );
    }
});
</script>

// src/renderer/view/components/SideBarRemotes.tsx
import * as vca from "vue-tsx-support/lib/vca";
import SideBarBase from "./SideBarBase";
import { useRootModule } from "view/store";

export default vca.component({
  name: "SideBarRemotes",
  setup() {
    const rootModule = useRootModule();
    return () => (
      <SideBarBase title="Remotes" hide={rootModule.actions.hideSidebar}>
        Not implemented
      </SideBarBase>
    );
  }
});
